apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: grafana
    targetRevision: 6.45.6 
    helm:
      values: |
        persistence:
          enabled: true
          size: 10Gi
        adminPassword: "123"
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

