apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/volk22kamin/argoCD.git
    path: charts/jenkins 
    targetRevision: tgz-charts
    helm:
      valueFiles:
        - values.yaml
        - override-vals.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
