apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: low-jenkins
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    values:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - low
    repoURL: https://github.com/volk22kamin/jenkins-chart.git
    path: jenkins-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - override-vals.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

