argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
        type: NodePort
        nodePortHttp: 30082
    extraArgs:
      - --insecure
  configs:
    cm:
      accounts.crunchops: login
      accounts.zeev: login  
    rbac:
      policy.csv: |
        p, role:readonly, applications, get, *, allow
        g, crunchops, role:readonly
        g, zeev, role:readonly
