argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      type: NodePort
      nodePortHttp: 30082
    extraArgs:
    - --insecure
  configs:
    cm:
      exec:
        enabled: true
      accounts.crunchops: login
      accounts.zeev: login
      accounts.maor: login

      accounts.user1: login
      accounts.user2: login
      accounts.user3: login
      accounts.user4: login

    rbac:
      policy.csv: |-
        p, role:readonly, applications, get, *, allow
        p, role:monitoring-application-list, applications, get, */monitoring-*, allow
        p, role:developer, applications, *, *, allow
        p, role:todo, applications, get, */to-do*, allow
        
        g, zeev, role:admin

        g, todo-team, role:todo

        g, user1, todo-team
        g, user2, todo-team
        g, user3, todo-team
        g, user4, todo-team


