argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      type: NodePort
      nodePortHttp: 30082
    extraArgs:
    - --insecure
  configs:
    cm:
      accounts.crunchops: login
      accounts.zeev: login
      accounts.maor: login

      accounts.user1: login
      accounts.user2: login
      accounts.user3: login
      accounts.user4: login

    rbac:
      policy.csv: |-
        p, role:readonly, applications, get, *, allow
        g, crunchops, role:readonly
        p, role:monitoring-application-list, applications, get, */monitoring-*, allow
        p, role:todo, applications, get, *, allow
        g, zeev, role:monitoring-application-list
        p, role:developer, applications, *, *, allow
        g, maor, role:developer
        g, monitor-group, role:todo

        g, user1, monitor-group
        g, user2, monitor-group
        g, user3, monitor-group
        g, user4, monitor-group


