argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      type: NodePort
      nodePortHttp: 30083
    extraArgs:
    - --insecure
  configs:
    cm:
      exec.enabled: true
