argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
        type: NodePort
        nodePortHttp: 30082
    extraArgs:
      - --insecure
