argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    service:
      type: NodePort
      nodePortHttp: 30082
    extraArgs:
    - --insecure
  configs:
    cm:
      exec.enabled: true
      accounts.zeev: login
      accounts.maor: login

      accounts.user1: login
      accounts.user2: login
      accounts.user3: login
      accounts.user4: login

    rbac:
      policy.csv: |-
        p, role:readonly, applications, get, *, allow
        


