argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: true
  server:
    service:
      type: NodePort
      nodePortHttp: 30082
    extraArgs:
    - --insecure
  configs:
    cm:
      exec.enabled: true
    #   accounts.zeev: login,apiKey
    # rbac:
    #   policy.csv: |-
    #     g, zeev, role:admin
