apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: dev
roleRef:
  kind: ClusterRole
  name: argocd-cluster-role
  apiGroup: rbac.authorization.k8s.io
